name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          # only caches if package-lock.json dependancies change and checks for os
          key: ${{ runner.os }}=node-${{ hashFiles('**/package-lock.json') }}
          # look for cached key. If none, create one from above
          restore-keys: |
            ${{ runner.os }}=node-
      - name: Use NodeJs Version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci
      - name: Check Code Formatting
        run: npm run format:check
      - name: Run Unit Tests
        run: npm test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain strange-winter.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
