name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use NodeJs Version
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install Dependencies
        run: npm ci
      - name: Check Code Formatting
        run: npm run format:check
      - name: Run Unit Tests
        run: npm test -- --coverage
        env:
          CI: true
